labels:
  - name: feat
    color: 0E8A16
    description: Related to new features and implmentations
  
  - name: bug
    color: B60205
    description: Related to non-working things or strange behaviors
  
  - name: doc
    color: 0052CC
    description: Related to documentation, project illustrations
  
  - name: infra
    color: FBCA04
    description: Related to repository and infra stuff
  
  - name: explo
    color: D93F0B
    description: Related to new things I don't know how to do
  
  - name: "[US] developer"
    color: C2E0C6
    description: As a developer, I want to [...]
  
  - name: "[US] user"
    color: C5DEF5
    description: As a user, I want to [...]
  
  - name: "[US] repowner"
    color: D4C5F9
    description: As a repowner, I want to [...]
  