version: "3.8"

services:
  app:
    container_name: cofy_app
    build:
      context: app/
      dockerfile: ../.docker/app/dev.Dockerfile
    volumes:
      - ./app:/go/src/github.com/blyndusk/cofy/app
    networks:
      - cofy
  api:
    container_name: cofy_api
    build:
      context: api/
      dockerfile: ../.docker/api/dev.Dockerfile
    ports:
      - 3003:3003
    volumes:
      - ./api:/go/src/github.com/blyndusk/cofy/api
    networks:
      - cofy

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cofy

  adminer:
    image: adminer
    restart: always
    ports:
      - 3002:8080
    depends_on:
      - postgres
    networks:
      - cofy

volumes:
  postgres:

networks:
  cofy:
