name: DOCKER

on:
  push:
    branches:
      - main

jobs:
  DOCKER:
    name: DOCKER
    runs-on: ubuntu-latest
    steps:
      - name: 1 - CHECKOUT
        uses: actions/checkout@v2

      - name: 2 - BUILD + PUSH DOCKER IMG TO GITHUB PACKAGE REGISTRY
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GPAT }}
          registry: docker.pkg.github.com
          repository: blyndusk/repo-template/pyapp
          tags: "latest"