name: PYTHON

on: [push]

jobs:
  LINT:
    name: LINT
    runs-on: ubuntu-latest
    steps:
    - name: 1 - CHECKOUT
      uses: actions/checkout@v2

    - name: 2 - SETUP PYTHON@3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: 3 - INSTALL
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: 4 - LINT
      run: |
        pylint `ls -R|grep .py$|xargs`
